### ISSUE TITLE
Empty Toolbar Menu On Linux

### ISSUE THREAD

**Issue by AmirAbrams** [SilkNetwork/Silk-Core#5]
## Describe the issue
Silk Linux Toolbar  menu drop down is empty.

### Steps to reproduce
1. Launch silk-qt on Linux
2. Click on the OS toolbar
3. Menu is blank

### Expected behavior
Tell us what should happen
* It should show the menu items.

### Actual behavior
Tell us what happens instead
* Shows an empty drop down menu (see image)

### Screenshots
![silkcoin-menu issue](http://i.imgur.com/trvpVdI.png)

### What platform are you using (Linux, Windows, Mac)
Ubuntu Linux 16.04 64 bit version

**Comment by GregoryBetz** [comment]
Ahhh this happened with DarkSilk randomly after Argon2d was put in in the spring. Super frustrating. I don't think we ever fixed it because the next iteration of Argon2d params came pretty quickly and the problem solved itself. Maybe that will happen again? ha

**Comment by empinel** [comment]
Could be related to https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

**Comment by SCDeveloper** [comment]
Uh oh!

Something has gone wrong. We're sorry!
If we are in the middle of an update, Launchpad will be back in a couple of minutes. Otherwise, we are working to fix the unexpected problems. Check @launchpadstatus on Twitter for updates.

If the problem persists, let us know in the #launchpad IRC channel on freenode.

Technically, the load balancer took too long to connect to an application server.

Reload this page or try again in a few minutes

**Comment by empinel** [comment]
That's a problem in LaunchPad which is temporary - check out @launchpadstatus on Twitter

**Comment by spencerlievens** [comment]
sudo apt-get remove appmenu-qt5 before building the wallet?

Have you tested?

**Comment by empinel** [comment]
No - I read this somewhere on a similar problem

**Comment by spencerlievens** [comment]
Closing as not a codebase issue.
